# Generated by Django 4.1.1 on 2022-11-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='is_optional',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=10),
        ),
    ]
