# Generated by Django 4.1.1 on 2022-11-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0002_alter_ingredient_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
