# Generated by Django 4.1.1 on 2022-11-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0003_alter_ingredient_ingredient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_activated',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=10),
        ),
    ]
